/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ilp007proj002;

import java.io.File;

/**
 *
 * 
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    /**
     * Creates new form JFrame
     */
    public TelaPrincipal() {
        initComponents();
        this.getContentPane().setBackground(Cores.COR_FUNDO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPessoas = new javax.swing.JButton();
        btnJokenpo = new javax.swing.JButton();
        btnQuiz = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblParticipantes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(640, 480));

        btnPessoas.setBackground(Cores.COR_INPUT);
        btnPessoas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ilp007proj002/icones/pessoa.png"))); // NOI18N
        btnPessoas.setText("Pessoas");
        btnPessoas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPessoasActionPerformed(evt);
            }
        });

        btnJokenpo.setBackground(Cores.COR_INPUT);
        btnJokenpo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ilp007proj002/icones/jokenpo.png"))); // NOI18N
        btnJokenpo.setText("Jokenpo");
        btnJokenpo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnJokenpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJokenpoActionPerformed(evt);
            }
        });

        btnQuiz.setBackground(Cores.COR_INPUT);
        btnQuiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ilp007proj002/icones/quiz.png"))); // NOI18N
        btnQuiz.setText("Quiz");
        btnQuiz.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuizActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitulo.setText("ILP007_PROJ002");

        lblParticipantes.setText("Nome dos participantes do grupo: Italo e Tiago");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lblTitulo))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnQuiz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnJokenpo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(lblParticipantes)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(23, 23, 23)
                .addComponent(btnPessoas)
                .addGap(18, 18, 18)
                .addComponent(btnJokenpo)
                .addGap(18, 18, 18)
                .addComponent(btnQuiz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblParticipantes, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPessoasActionPerformed
        this.dispose();
        new TelaPessoas().setVisible(true);
    }//GEN-LAST:event_btnPessoasActionPerformed

    private void btnQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuizActionPerformed
        this.dispose();
        new TelaQuiz().setVisible(true);
    }//GEN-LAST:event_btnQuizActionPerformed

    private void btnJokenpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJokenpoActionPerformed
        this.dispose();
        new TelaJokenpo().setVisible(true);
    }//GEN-LAST:event_btnJokenpoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                if (new File("./db.json").exists()) {
                    ControleIO.carregar();
                }
                TelaPrincipal telaPrincipal = new TelaPrincipal();               
                
                telaPrincipal.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJokenpo;
    private javax.swing.JButton btnPessoas;
    private javax.swing.JButton btnQuiz;
    private javax.swing.JLabel lblParticipantes;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
