/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ilp007proj002;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.Timer;

/**
 *
 * 
 */
public class TelaQuiz extends javax.swing.JFrame {

    /**
     * Creates new form TelaQuiz
     */
    public TelaQuiz() {
        initComponents();
        this.getContentPane().setBackground(Cores.COR_FUNDO);
        lblRespostaCerta.setVisible(false);
        scrollPanePerguntas.setVisible(false);
        radioResposta1.setVisible(false);
        radioResposta2.setVisible(false);
        radioResposta3.setVisible(false);
        radioResposta4.setVisible(false);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupRespostas = new javax.swing.ButtonGroup();
        btnVoltar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        radioResposta1 = new javax.swing.JRadioButton();
        radioResposta2 = new javax.swing.JRadioButton();
        radioResposta3 = new javax.swing.JRadioButton();
        radioResposta4 = new javax.swing.JRadioButton();
        btnEnviar = new javax.swing.JButton();
        lblRespostaCerta = new javax.swing.JLabel();
        scrollPanePerguntas = new javax.swing.JScrollPane();
        txtAreaPerguntas = new javax.swing.JTextArea();
        lblNumPerguntas = new javax.swing.JLabel();
        cmbNumPerguntas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVoltar.setBackground(Cores.COR_INPUT);
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitulo.setText("Quiz");

        radioResposta1.setBackground(Cores.COR_INPUT);
        btnGroupRespostas.add(radioResposta1);
        radioResposta1.setText("1");
        radioResposta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioResposta1ActionPerformed(evt);
            }
        });

        radioResposta2.setBackground(Cores.COR_INPUT);
        btnGroupRespostas.add(radioResposta2);
        radioResposta2.setText("2");
        radioResposta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioResposta2ActionPerformed(evt);
            }
        });

        radioResposta3.setBackground(Cores.COR_INPUT);
        btnGroupRespostas.add(radioResposta3);
        radioResposta3.setText("3");

        radioResposta4.setBackground(Cores.COR_INPUT);
        btnGroupRespostas.add(radioResposta4);
        radioResposta4.setText("4");

        btnEnviar.setBackground(Cores.COR_INPUT);
        btnEnviar.setText("Iniciar");
        btnEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnviarMouseClicked(evt);
            }
        });

        lblRespostaCerta.setText("Resposta certa...");

        txtAreaPerguntas.setEditable(false);
        txtAreaPerguntas.setBackground(Cores.COR_INPUT);
        txtAreaPerguntas.setColumns(20);
        txtAreaPerguntas.setRows(5);
        txtAreaPerguntas.setText("Dados das perguntas...");
        scrollPanePerguntas.setViewportView(txtAreaPerguntas);

        lblNumPerguntas.setText("Número de perguntas:");

        cmbNumPerguntas.setBackground(Cores.COR_INPUT);
        cmbNumPerguntas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "4", "5", "6", "7", "8", "9", "10" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltar)
                        .addGap(203, 203, 203)
                        .addComponent(lblTitulo))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblRespostaCerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNumPerguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbNumPerguntas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(btnEnviar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioResposta4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radioResposta3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radioResposta2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radioResposta1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(scrollPanePerguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(lblTitulo))
                .addGap(26, 26, 26)
                .addComponent(lblRespostaCerta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPanePerguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioResposta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioResposta2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioResposta3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioResposta4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumPerguntas)
                    .addComponent(cmbNumPerguntas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEnviar)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
        new TelaPrincipal().setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void radioResposta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioResposta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioResposta1ActionPerformed
    static int[] ordenacaoPerguntas = JogoPerguntas.jogar().clone();
    static int perguntaAtual = 0;
    static int resposta = 0;
    static int respostasCertas = 0;
    static int numPerguntas = 0;
    static String pergunta[] = {};
    private void btnEnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnviarMouseClicked
        //iniciar ou reiniciar
        if(perguntaAtual == 0){
            numPerguntas = Integer.parseInt(cmbNumPerguntas.getSelectedItem().toString());
            lblNumPerguntas.setVisible(false);
            cmbNumPerguntas.setVisible(false);
            lblRespostaCerta.setVisible(false);
            scrollPanePerguntas.setVisible(true);
            radioResposta1.setVisible(true);
            radioResposta2.setVisible(true);
            radioResposta3.setVisible(true);
            radioResposta4.setVisible(true);
            btnEnviar.setText("Responder");}
        //colocar pergunta na tela
        if(perguntaAtual < numPerguntas){
            pergunta = JogoPerguntas.listaPerguntas[ordenacaoPerguntas[perguntaAtual]].enunciar().clone();
            txtAreaPerguntas.setText(pergunta[0]);
            radioResposta1.setText(pergunta[1]);
            radioResposta2.setText(pergunta[2]);
            radioResposta3.setText(pergunta[3]);
            radioResposta4.setText(pergunta[4]);
        }
        //atualizar a pergunta //coloquei separado por causa da verificação de baixo que precisa de -2
        if(perguntaAtual< numPerguntas+1){
            perguntaAtual += 1;
        }
        //verificar resposta
        if(perguntaAtual > 1 && perguntaAtual<numPerguntas+2){
            Enumeration<AbstractButton> botões = btnGroupRespostas.getElements();
            while(botões.hasMoreElements()) {
                AbstractButton botão = botões.nextElement();
                if (botão.isSelected()) {
                     char respostaChar = (botão.getText()).charAt(0);
                     resposta = Integer.parseInt(String.valueOf(respostaChar));
                }
            } 
            boolean acertou = JogoPerguntas.listaPerguntas[ordenacaoPerguntas[perguntaAtual-2]].responder(resposta);
            respostasCertas += acertou?1:0;
            String resultado = acertou?"Você acertou!":"Você errou!";
            lblRespostaCerta.setVisible(true);
            lblRespostaCerta.setText("A resposta era " + JogoPerguntas.listaPerguntas[ordenacaoPerguntas[perguntaAtual-2]].respostas[JogoPerguntas.listaPerguntas[ordenacaoPerguntas[perguntaAtual-2]].respostaCerta-1] + ". " + resultado);
            ActionListener apagarLabelRespostaCerta;
            apagarLabelRespostaCerta = (ActionEvent event) -> {
                lblRespostaCerta.setVisible(false);
            };
            Timer timer;
            timer = new Timer(2500, apagarLabelRespostaCerta);
            timer.setRepeats(false);
            timer.start();    
        }
        //finalizar o quiz
        if(perguntaAtual == numPerguntas+1){
            ActionListener mostrarResultadoFinal;
            mostrarResultadoFinal = (ActionEvent event) -> {
                lblRespostaCerta.setVisible(true);
                lblRespostaCerta.setText("Sua taxa de acerto foi de " + Math.round(respostasCertas*100.00/numPerguntas*100.00)/100.00 + "%");
                respostasCertas = 0;
                numPerguntas = 0;
            };
            Timer timer;
            timer = new Timer(3000, mostrarResultadoFinal);
            timer.setRepeats(false);
            timer.start();   
            scrollPanePerguntas.setVisible(false);
            radioResposta1.setVisible(false);
            radioResposta2.setVisible(false);
            radioResposta3.setVisible(false);
            radioResposta4.setVisible(false);
            lblNumPerguntas.setVisible(true);
            cmbNumPerguntas.setVisible(true);            
            ordenacaoPerguntas = JogoPerguntas.jogar().clone();
            perguntaAtual = 0;
            resposta = 0;
            btnEnviar.setText("Reiniciar");
        }
    }//GEN-LAST:event_btnEnviarMouseClicked

    private void radioResposta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioResposta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioResposta2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.ButtonGroup btnGroupRespostas;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cmbNumPerguntas;
    private javax.swing.JLabel lblNumPerguntas;
    private javax.swing.JLabel lblRespostaCerta;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton radioResposta1;
    private javax.swing.JRadioButton radioResposta2;
    private javax.swing.JRadioButton radioResposta3;
    private javax.swing.JRadioButton radioResposta4;
    private javax.swing.JScrollPane scrollPanePerguntas;
    private javax.swing.JTextArea txtAreaPerguntas;
    // End of variables declaration//GEN-END:variables
}
