/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ilp007proj002;

import java.util.Random;

/**
 *
 * 
 */
public class TelaJokenpo extends javax.swing.JFrame {

    private TelaPartidaJokenpo telaPartidaJokenpo;
    /**
     * Creates new form TelaJokenpo
     */
    static Pessoa[] participantesVetorStatic = new Pessoa[8];
    public TelaJokenpo() {
        initComponents();
        this.getContentPane().setBackground(Cores.COR_FUNDO);
        txtAreaParticipantes.setBackground(Cores.COR_INPUT);
        Pessoa[] participantesVetor = new Pessoa[8];
        int numParticipantes = 0;
        //inserir o jogador
        participantesVetor[0] = null;
        numParticipantes += 1;
        //inserir as pessoas
        for(int i = 1;i<=ControleIO.database.pessoas.size() && numParticipantes < 8;i++){
            participantesVetor[i] = (Pessoa)ControleIO.database.pessoas.get(i-1);
            numParticipantes += 1;
        }
        //inserir os médicos
        for(int i = 1;i<=ControleIO.database.medicos.size() && numParticipantes < 8;i++){
            participantesVetor[numParticipantes] = (Medico)ControleIO.database.medicos.get(i-1);
            numParticipantes += 1;
        }
        //caso não tenha 8 participantes
        if(numParticipantes < 8){
            JScrollPaneParticipantes.setVisible(false);
            btnIniciar.setVisible(false);
            lblParticipantes.setText("Faltam participantes. Crie mais " + (8-numParticipantes) + " participantes para jogar.");
        }
        //caso tenha
        else{
            txtAreaParticipantes.setText("Você ");
            for(int i = 1;i<= 7;i++){
                txtAreaParticipantes.setText(txtAreaParticipantes.getText() + "\n" + participantesVetor[i].nome);
            }
            //embaralhar os participantes
            Random random = new Random();
            for (int i = 0; i < 8; i++) {
                int j = random.nextInt(8);
                Pessoa temp = participantesVetor[i];
                participantesVetor[i] = participantesVetor[j];
                participantesVetor[j] = temp;
            }
            participantesVetorStatic = participantesVetor.clone();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        lblParticipantes = new javax.swing.JLabel();
        JScrollPaneParticipantes = new javax.swing.JScrollPane();
        txtAreaParticipantes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVoltar.setBackground(Cores.COR_INPUT);
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitulo.setText("Jokenpo");

        btnIniciar.setBackground(Cores.COR_INPUT);
        btnIniciar.setText("Iniciar Torneio");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        lblParticipantes.setText("Lista de Participantes:");

        txtAreaParticipantes.setColumns(20);
        txtAreaParticipantes.setRows(5);
        JScrollPaneParticipantes.setViewportView(txtAreaParticipantes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JScrollPaneParticipantes)
                            .addComponent(lblParticipantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(btnIniciar)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltar)
                .addGap(5, 5, 5)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblParticipantes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JScrollPaneParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btnIniciar)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
        telaPartidaJokenpo.listaParticipantes = participantesVetorStatic.clone();
        new TelaPrincipal().setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        this.dispose();
        telaPartidaJokenpo.listaParticipantes = participantesVetorStatic.clone();
        this.telaPartidaJokenpo = new TelaPartidaJokenpo();
        this.telaPartidaJokenpo.setVisible(true);
        //new TelaPartidaJokenpo().setVisible(true);
    }//GEN-LAST:event_btnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJokenpo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJokenpo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJokenpo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJokenpo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJokenpo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPaneParticipantes;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lblParticipantes;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextArea txtAreaParticipantes;
    // End of variables declaration//GEN-END:variables
}
